env: "local"
server:
  port: ":8001"
postgres:
  user: "postgres"
  pass: "root"
  port: "8092"
  host: "localhost"
  name: "mymedos"
  reload: false
email:
  reciever: "wwww@gmail.com"
  sender: "qqqq@gmail.com"
  password: "qwerqweqwrq"